### ISSUE TITLE
2 Game specific Crashes

### ISSUE THREAD

**Issue by HenryHeliolisk** [Atmosphere-NX/Atmosphere#1154] opened 2020-09-17 11:00 UTC
on the latest version of atmosphere: 0.14.3,
When you play super Mario all stars, and play Super Mario 64, if you close out using the select press menu, the entire console crashes.

Also, for super smash brothers ultimate, when It starts up, everything is fine but when I select my character to fight, the music still plays but the screen goes dark, I heard the this is a sysmodule problem, but I need to know how I would go about fixing it.

**Comment by fincs** [comment] 2020-09-17 11:01
Duplicate of https://github.com/Atmosphere-NX/Atmosphere/issues/1153

**Closed by fincs** 2020-09-17 11:01 UTC

**Comment by cheesycod** [comment] 2020-09-17 11:14
> Also, for super smash brothers ultimate, when It starts up, everything is fine but when I select my character to fight, the music still plays but the screen goes dark, I heard the this is a sysmodule problem, but I need to know how I would go about fixing it.

Try removing all custom system modules and try again. Next time, please use the ReSwitched Discord as this is not a support forum
