### ISSUE TITLE
Crash after pressing home button in softwares like goldleaf

### ISSUE THREAD

**Issue by blawar** [Atmosphere-NX/Atmosphere#508] opened 2019-04-12 15:43 UTC
Bug Report
What's the issue you encountered?
Crash after pressing home button in softwares like goldleaf

How can the issue be reproduced?
Boot into Atmosphère 0.8.7, plug in the usb cable and connect to PC, open goldleaf, install title over usb, press home.

Crash Report
https://gist.github.com/TachibanaSuzume/70f27d0b56019d3348b11053ea70b856

System Firmware Version
7.0.1

Environment?
Hetake & Atmosphère 0.8.7.
Or just sending fusee-primary.bin

Additional context?
N/A

**Comment by fincs** [comment] 2019-04-12 15:46
Duplicate of #506.

**Closed by fincs** 2019-04-12 15:46 UTC
Labels: duplicate
