### ISSUE TITLE
Feature suggestion: Profile-specific game language selection

### ISSUE THREAD

**Issue by klauskopec** [Atmosphere-NX/Atmosphere#2098] opened 2023-04-18 11:04 UTC
Feature suggestion: please add profile-specific game language selection. Currently, we can select language per game, but not per profile (person) currently playing the game.

Use case: I play games in English, my kids play the same games in our local language. Currently, we have to switch languages (e.g. Using nx locale switcher) every time we switch who's playing.

**Comment by DraconicNEO** [comment] 2023-04-19 05:31
I think this is a duplicate of #547 to elaborate on that one it was declined since per user configs based on GUID would be too hard to manage.

**Comment by SciresM** [comment] 2023-04-19 05:31
Yeah, pretty much. No good way to specify a user in text.

**Comment by DraconicNEO** [comment] 2023-04-19 05:32
> Yeah, pretty much. No good way to unambiguously specify a user in text.

Yeah it was also explained in #547

**Closed by SciresM** 2023-04-19 05:31 UTC

**Comment by klauskopec** [comment] 2023-04-19 06:04
Thanks for clarifying, didn't see the other one.

I guess if you enabled it while suggesting a ui-based tool to make those changes it might work as that tool could likely read the user id. But I understand it's difficult if you want to keep it without any ui.
