### ISSUE TITLE
failed to stat stage2

### ISSUE THREAD

**Issue by JhonJhonny** [Atmosphere-NX/Atmosphere#316] opened 2019-01-04 17:24 UTC
### What's the issue you encountered?
Couldn't launch atmosphere cause of "failed to stat2(atmosphere/fusee-secondary.bin)!"
### How can the issue be reproduced?
tried on a switch with 4.1.0 fw with the manual update for the exfat support
### Crash report?
none
(If a crash report was created under /atmosphere/crash_reports/, please upload it to 
[gist](https://gist.github.com/) and paste the link here.)

### Environment?

- What bootloader (fusee, hekate, etc) was Atmosphère launched by:fusee
- Official release or unofficial build:tried with 0.8.2/0.7.5/0.7.0
- Do you have additional kips you're loading:
- Additional info about your environment:
tried with 2 different sd both in fat32 and exfat, same issue occurring

**Comment by JhonJhonny** [comment] 2019-01-05 11:11
The stage 2 error was out of no where, i use the 0.8.2 release, i'm dure
the fusee-secondari.bin is there and actually there's not much to do other
than drag and drop so I believe it's pretty hard to miss some files.
Don't think it's a micro sd, ora a reader problem cause I can boot reinx
and Sxos (I bought time ago) without any problem. But the most recurrent
error is the other one "failed to mount at least one partition"
If I have any other thing to try out I will be more than glad to try
Thanks in advance

Il giorno sab 5 gen 2019, 07:21 tiliarou <notifications@github.com> ha
scritto:

**Comment by JhonJhonny** [comment] 2019-01-05 11:12
The different errors I believe come out from different version of
atmosphere that I tried

Il giorno sab 5 gen 2019, 12:11 Jona Favaro <jonafav18@gmail.com> ha
scritto:

**Comment by SciresM** [comment] 2019-01-10 00:55
This sounds like bad SD card/SD card reader.  Also, duplicate of #315.

**Closed by SciresM** 2019-01-10 00:55 UTC

**Comment by JhonJhonny** [comment] 2019-01-10 00:58
How come i can boot both sxos and Reinx?
It sucks, i war really interested in atmosphere, I tried other only to see
If those worked after atmosphere didn't.. can it really be only an ad
card/reader error?

Il giorno gio 10 gen 2019, 01:55 SciresM <notifications@github.com> ha
scritto:
