### ISSUE TITLE
Controllers are disconnecting

### ISSUE THREAD

**Issue by Calisto02** [Atmosphere-NX/Atmosphere#1704] opened 2021-11-08 17:01 UTC
### What's the issue you encountered?
Hello, again. The issue I am having are my joy-cons not staying connected to my switch, I've tried using 3 different pairs of controllers, 2 which were working fine before updating, and I went out and bought a new pair to test and they do the same thing. I haven't been doing anything besides playing games, and I did have tesla overlay and Edizon installed. Like I have mentioned in my other post. I cleared out and factory reseted my switch and formatted my SD card so everything was fresh and the issue still happens. I can play on OFW just fine, this only happens when I launch atmosphere. I made sure to remove all custom system modules.

### How can the issue be reproduced?
I'm unsure how to reproduce exactly. It just happens at random intervals. Even at the home screen. Sometimes I can play for 10 or maybe 30 minutes straight before my controllers are forcefully disconnected. 

### Crash Report
N/A My switch hasn't crashed.

### System Firmware Version
13.1.0

### Environment?
The bootloader I use is hekate, The problem started since Atmosphere version 1.2.1 and onwards on all official releases. 

I did have sys modules, Tesla overlay, Edizon Overlay, but like I said above I removed those afterwards. 

Software I had installed before resetting: ftpd pro, HB app store, Hekate toolbox, JKSV, EdizonSE, All-In-One Switch updater.

And I'm using SysNAND

### Additional context?

If you need anymore info, just ask, I'm unsure what else I can provide as I haven't received crashes.

**Comment by SciresM** [comment] 2021-11-08 17:04
Could you post a screenshot of /atmosphere/contents folder so we can check/verify no sysmodules which might be interfering?

I actually have literally no idea how normal ams could interfere in this, so hopefully it's something like that indeed.

**Comment by Calisto02** [comment] 2021-11-08 17:11
Like I said I have a fresh install now of atmosphere, that folder is empty now
![Capture](https://user-images.githubusercontent.com/93935836/140787131-9f0f8fe5-6a3a-4c3d-b4ea-10d70e7e10c3.PNG)
.

**Comment by SciresM** [comment] 2021-11-08 17:12
Hmmm. 

I have no idea what in AMS could possibly cause this and no idea how to debug this.

Join ReSwitched discord for technical discussion of problem, I suppose, but :/

**Comment by SciresM** [comment] 2021-11-08 17:13
I guess @ndeadly any ideas? You've worked with controller stuff a lot.

**Comment by Calisto02** [comment] 2021-11-08 17:14
This only started for me once I updated to 13.1.0 and atmosphere 1.2.1, Before that everything worked just fine

**Comment by SciresM** [comment] 2021-11-08 17:15
Does the issue occur booting into stock (13.1.0 without atmosphere?)

That should be informative, I think.

**Comment by Calisto02** [comment] 2021-11-08 17:16
I still get the problem but it isn't as bad. My controllers might disconnect every hour or so instead of minutes

**Comment by SciresM** [comment] 2021-11-08 17:17
Yeah. I believe this is a real issue for you and I even believe that atmosphere exacerbates it.

I just literally have zero clue where to even begin looking into something like this to help you.

**Comment by Calisto02** [comment] 2021-11-08 17:20
That's okay, I can still play my games just with the annoyance of the disconnects. I was just hoping maybe someone else might've had this problem and there was an easy fix. I'm unsure what changed from 13.0.0 to 13.1.0, but something changed how the controllers sync or something to my switch. Thank you though. If you need anything else from my switch I can send it over.

**Comment by SciresM** [comment] 2021-11-08 17:21
Yeah. Maybe ndeadly will have something to add that might be useful for investigating this.

I'll leave the issue open for a while, given any leads I am happy to spend time/energy looking at this for you.

**Comment by Calisto02** [comment] 2021-11-08 17:23
Thank you so much! I'm sorry for the other post I did.

**Comment by LittleWhite-tb** [comment] 2021-11-08 20:07
Hello,

I have a, somewhat, similar issues with the right joycon and sometimes the left. As far as I could tell, it could be related to the electric contacts (between the rails and the joycon) not being as good as in the first days of the Switch. So, for me, it happens in handheld mode, joycons attached.
I could not find back a list of possible ways for fixing this, but you can do this simple one:
- add some paper with rubber tape on the "arrows" on the rail part of the joycon, there:
![joy](https://user-images.githubusercontent.com/8618754/140809824-741dcb00-3bb7-4915-b34d-f3da93ea6d87.png)
This will push the joycons towards the pins of the Switch and make the contacts more stable/less sensible to electric disconnection.

**Comment by Calisto02** [comment] 2021-11-08 20:12
Thank you, once I get home after work I will give this a try to see if it fixes it.

**Comment by ndeadly** [comment] 2021-11-08 22:50
@SciresM I have definitely noticed a few strange controller issues like this being reported since 13.0.0, but since I haven't been able to reproduce anything myself and they're not being widely reported I chalked them up to user error. Maybe there's actually more to it.

I don't have any immediate suggestions of what the cause could be, especially since this appears to be happening on stock firmware too. Maybe running an up to date build of the uart_mitm branch of Atmosphere and creating an HCI log might help shed some light on the reason for disconnection? That's probably where I'd start, to see whether the console is explicitly closing the hid connection or there's some kind of connection error occuring etc.

**Comment by Calisto02** [comment] 2021-11-09 01:00
Hey, I tried what “Littlewhite-tb” recommend with the tape and I can confirm it’s nothing hardware related in terms of the pins. I still kept getting the same issue.

**Comment by Calisto02** [comment] 2021-11-09 04:01
So I’m not that knowledgeable in terms of how things work so I’m sorry if this sounds stupid. 
but since I’m using atmosphere in the sysnand can any sort of sys modules somehow break or corrupt system files? I didn’t want to put atmosphere on my second switch but I did to see if the same issue happens, but it doesn’t, I even installed everything I had before and it works fine on my second switch. I’m unsure how or why my main switch is acting up like this with atmosphere.

**Comment by base97** [comment] 2021-11-10 08:58
If it helps ... I have the same controller issue on one of my switches and all began somewhere around fw 12.0.1 or something like that (the before last controller update that came with OFW) ... first it was solved by leaving the bluetooth connection on while playing in handheld mode, but this didn't last very long, then what i tried was every time i got multiple disconnection issues in a row just put the console in sleep mode (power button) and after a few seconds turn it back on (sometime 2 or 3 times in a raw) until the connection was stable (keep in mind that my controller got disconnected every 2 to 5 seconds while playing mostly ACNH // also going into inventory - exiting/entering houses, triggered the issues instantly) 
The best solution in my case was to go back to the original Joycons that came with the console (had to replace control-sticks because they where busted, not just drifting) but at least i don't have the issue any more ... hopefully :)
The other solution (not as stable) was to change just the controller that got disconnected until you find a stable pair (not very handy cause you need multiple controller pairs)

**Comment by base97** [comment] 2021-11-10 09:41
Forgot to mention environment .. OFW 13.1.0 ... CFW AMS 1.2.2 on fw 13.1.0 on emmunand booting through Hekate 5.6.5/fusee... installed apps tesla overlay/emuiibo - jksv - awoo installer - Hb+Daybreak "build in" from athmosphere

**Comment by kumibrr** [comment] 2021-11-10 14:51
I've got the exact same issue. in OFW 13.1.0 my right joycon behaves as expected, but when I launch atm in my emunand with fusee it doesn't connect wirelessly no matters what I try. Only happens with the right joycon.

**Comment by nemopsp** [comment] 2021-11-12 03:39
I am having this issue as well. OFW 13.1.0 ... CFW AMS 1.2.4 on fw 13.1.0 sysnand. As soon as I disconnect jon cons the system does not even try to connect to them. Also my other two set on jon cons wont connect either nor the pro controller. I manual try to get them to connect and nothing. Furthermore, I downgraded to CFW AMS 1.2.2 and now they will connect, however I also notice on both version the system do not like to wake up from sleep right away. Also after I put the system to sleep and woke it up. The controllers no longer will connect. Only fix I found is to reboot the system and they connect again. So im not sure when the system sleeps it also put the bluetooth in a deep sleep and never wakes up. Anyways I hope these extra details help you fix it in next release.

**Comment by zemixe** [comment] 2021-11-12 04:13
> I am having this issue as well. OFW 13.1.0 ... CFW AMS 1.2.4 on fw 13.1.0 sysnand. As soon as I disconnect jon cons the system does not even try to connect to them. Also my other two set on jon cons wont connect either nor the pro controller. I manual try to get them to connect and nothing. Furthermore, I downgraded to CFW AMS 1.2.2 and now they will connect, however I also notice on both version the system do not like to wake up from sleep right away(long delay). After I wake up the system the controllers no longer will connect. Only fix I found is to reboot the system and they connect again. So I'm not sure, but it seems like when I put the system to sleeps, it also puts the bluetooth in a deep sleep mode and never wakes up. Anyways I hope these extra details help you fix it in next release. My issue is more similar to #1705

This is nothing to do with atmosphere, remove the nx-btred sysmodule.

**Comment by tsukina22** [comment] 2021-11-15 05:43
> I still get the problem but it isn't as bad. My controllers might disconnect every hour or so instead of minutes

A friend of mine just had this problem today, before he was using sx os because some people put it there, then he call me to change it to just clean atmosphere.
Then i did, i updated everything to 13.1.0, and i put a clean atmosphere just to boot everything, i did a emunand for him too, just that, but i end up tooking it out because i thought the problem was the emunand, but even on Sysnand, his left joy con start to disconnected out of nowhere "please reconnect the Joycon to keep playing"  i asked if it was normal, and he said that it never happened before! 
I checked the Joycon and everything was really super locked, no room to even a slide, he even said to me that was new joycons that came like 5 months ago from Deal4b, because he Old ones appears some drift problem, but now everything is brand new and when he was on firmware 11.0.0 with sx os, this never happened before with the firmware 13.1.0, the Joycons just randomly disconnecting.

**Comment by Commander-Crash** [comment] 2021-11-22 17:30
Can Confirm this issue happens even when controllers are docked. Bought new joycons coz thats what i do when i have issues with Nintendo Hardware. And same happens in CFW. I never touch OFW.

**Comment by SciresM** [comment] 2021-11-22 18:20
I am considering locking this issue, because nobody commenting is contributing anything of value.

Unless your comment is actually informative, please do not make it -- there's no point, particularly since I'm unconvinced this is an issue that's actually atmosphere-caused (as the OP reports it in OFW, though it is maybe (how?) ams-exacerbated).

**Comment by Dokman** [comment] 2021-11-27 23:33
I confirm that i have the same issue, i'm on latest release and I am suffering disconnects, new joycons too.

**Comment by SciresM** [comment] 2021-11-27 23:49
@Dokman this comment falls into the useless category mentioned in the comment above yours.

There are no leads, ams does nothing that even could interfere with communications -- and the issue occurs in OFW as well.

Please only comment with technical commentary.

**Comment by ELY3M** [comment] 2022-04-20 20:51
I have same problem with one of my switch but I tried to clean the rails with electronic dust cleaner and toothbrush and put piece of paper on bottom between joy con and rail to help it.  it helps to clean the rails. I should try tape thing like someone said above here.   I am not blaming atmosphere.

**Comment by Commander-Crash** [comment] 2022-04-21 22:32
Issue still happens on 1.3.1 On OFW i have no issues.

**Comment by SciresM** [comment] 2022-04-21 22:51
Yeah, I'm closing this. I'm unconvinced this is actually a problem with atmosphere itself and not e.g. other sysmodules, and nobody has commented anything of value in several months.

**Closed** 2022-04-21 22:50 UTC

**Comment by kumibrr** [comment] 2022-04-22 06:19
> 

Yup, this issue can be solved by unlinking the joycons when switching from atmosphere to sysnand and viceversa.
I think it's safe to close.
