### ISSUE TITLE
Launching eshop through games freezes console. 

### ISSUE THREAD

**Issue by smrtg** [Atmosphere-NX/Atmosphere#808] opened 2020-01-30 14:32 UTC
### What's the issue you encountered?

Tried to launch the eshop through either Super Smash Bros Ultimate's shortcuts (to buy dlc) and Pokemon Shield's shortcuts (for the same reason) 

No changes were made by me to Atmosphere 

### How can the issue be reproduced?

Launch any game that can take you to the eshop for (mostly) dlc
Press the eshop shortcut 
Done, the eshop loading screen (the orange bars) should be frozen and the console also completely frozen too. 

### System Firmware Version

9.1.0

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
hekate
- Official release: 
  - 0.10.2|S
- Do you have additional kips or sysmodules you're loading:
sys-con
sys-ftpd-light
sys-clk
- Homebrew software installed: 

RetroArch
Atmosphere Updater
Browser (Internet browser)
Checkpoint 
EdiZon
Ftpd
Gamcard Installer
Goldleaf
HB App Store
Kosmos Toolbox
Kosmos Updater 
NXThemes Installer 
Reboot To Payload

**Comment by ELY3M** [comment] 2020-01-30 15:40
Can you buy thru the normal eshop?   I have no issues with using normal eshop.   I do have both of the games on game carts.  I never tried to access eshop inside the games.

**Comment by ELY3M** [comment] 2020-01-30 15:43
I just tested in pokemon sword and I can't reproduce the issues. it just forward to the normal eshop.

**Comment by ELY3M** [comment] 2020-01-30 16:41
are you running 90dns?   that will stop eshop from working.

**Comment by smrtg** [comment] 2020-01-30 20:23
Hey, tha ms for the reply. I can launch and buy from the home menu. I have both games digitally, don't know if that matters. And I'm not using 90dns. I can send a vid of it happening if you want. I've tried to launch eshop a total of ě times through an app, and all three is froze

**Comment by SciresM** [comment] 2020-01-30 20:25
Does error occur using stock atmosphere without custom sysmodules?

**Comment by smrtg** [comment] 2020-01-31 08:40
> Does error occur using stock atmosphere without custom sysmodules?

Haven't tried it yet. I'll try and post the result

**Comment by fennectech** [comment] 2020-02-17 21:12
Ive got the same issue here   ill grab an sd card and do it on plane jane atmosphere.

**Comment by SciresM** [comment] 2020-02-17 22:58
@fennectech "But yes this also happens on raw atmo" disagree.

That crash is from a service client being closed (terminated) in the middle of mitm session ACK. This can only happen if the process itself is terminated externally, which can never happen using stock atmosphere.

Also, the report you linked is unrelated to the freeze mentioned in the issue.

**Comment by fennectech** [comment] 2020-02-18 01:07
Ive got an sdcard with plain atmo (fusee-primary chainloaded with hekate) that exibits the hang. (not the crash)    i wasn not refering to that crash for the happening on atmo.

**Comment by SciresM** [comment] 2020-02-18 01:16
The hang as diagnosed so far only occurs with additional sysmodules present -- it's memory pool stuff.

It doesn't happen with stock atmosphere.

**Comment by ELY3M** [comment] 2020-02-21 05:39
note:  I am on stock atmosphere with sys-ftpd-light.

**Comment by hmax42** [comment] 2020-04-14 13:14
remove the sys-ftpd-light, that's a sysmodule

**Comment by SciresM** [comment] 2020-04-20 04:45
Still can't reproduce this using stock atmosphere. Closing.

**Closed by SciresM** 2020-04-20 04:45 UTC
