### ISSUE TITLE
Offer a way to still run games with fs_mitm mods while title_id=app is used

### ISSUE THREAD

**Issue by thedax** [Atmosphere-NX/Atmosphere#331] opened 2019-01-25 05:32 UTC
#### Overview:
If `title_id=app` is used, it's impossible to also play games with fs_mitm mods, since the override key will only launch the HBL or the game without mods depending on the override key setup. I propose that an additional key be added to temporarily ignore `title_id=app` so that titles with fs_mitm mods can still be used.

#### Smaller Details: 
N/A

#### Nature of Request:  
Change/Addition (falls under both)

### What component do you feel this would best fit within?
Stratosphere: loader

### Why would this feature be useful?

As it stands currently, the user has to manually edit `loader.ini`'s `title_id` entry back to a title id, put it back on the console, and reboot before it takes effect (a bug perhaps? IIRC loader is supposed to be able to do this on the fly).

This use-case would allow users who prefer the hbl to launch on any app to still be able to cancel that behaviour to enjoy games with mods.

**Comment by SciresM** [comment] 2019-01-25 07:42
Duplicate of #329

**Closed by SciresM** 2019-01-25 07:42 UTC

**Comment by thedax** [comment] 2019-01-25 10:13
I disagree, but alright.
