### ISSUE TITLE
hbmenu freeze on 0.10

### ISSUE THREAD

**Issue by reaps101** [Atmosphere-NX/Atmosphere#748] opened 2019-12-10 08:05 UTC
im running atmosphere 0.10.0 on firmware 4.0.1 and when in hbmenu and i push the home button my switch will lockup and i have to hold the power button for 12 seconds to turn it off 
there is no crash report

**Comment by SciresM** [comment] 2019-12-10 08:06
Does this only happen when opening hbl?

Does a hang occur opening album/games?

Do you have any custom system modules?

**Comment by reaps101** [comment] 2019-12-10 08:19
so in hbl i can press back and go through the folders soon as i press the home button it freezes
in the standard album if i press back it freezes
also in the controllers menu if i press close it freezes
i have no custom system modules only thing on sd card is atmosphere 0.10.0

**Comment by SciresM** [comment] 2019-12-10 08:21
Does the same hang occur when closing a game?

**Comment by reaps101** [comment] 2019-12-10 08:28
i didnt have any games installed but i just tried to put my zelda cartridge in and it wanted to download a game update and when i went to cancel it it froze

**Comment by SciresM** [comment] 2019-12-10 08:31
Please try to get a game launched -- I'm trying to tell if this is an applet exit problem or a general problem.

**Comment by SciresM** [comment] 2019-12-10 08:31
If you could message me on discord (SciresM#0524) that would be great.

**Comment by reaps101** [comment] 2019-12-10 10:42
sent u a message on discord think i did it right

**Comment by alimao10** [comment] 2019-12-10 17:36
I reported this problem but could not explain

**Comment by alimao10** [comment] 2019-12-12 23:04
https://www.youtube.com/watch?v=u6MbNYX1EfY

**Comment by alimao10** [comment] 2019-12-12 23:17
https://www.youtube.com/watch?v=AwF-F3qReX8

**Comment by alimao10** [comment] 2019-12-12 23:17
https://www.youtube.com/watch?v=Uq4ZDE391c8

**Comment by alimao10** [comment] 2019-12-12 23:33
https://www.youtube.com/watch?v=DSO__abNztM

**Comment by alimao10** [comment] 2019-12-12 23:34
sysnand 4.1atmosphere 0.9.4 not freezing

**Comment by SciresM** [comment] 2019-12-12 23:37
Please do not spam the issue tracker. The issue is known.

**Comment by alimao10** [comment] 2019-12-12 23:40
not spam sorry I'm showing the problem in videos, I will not report errors did not like

**Comment by misson20000** [comment] 2019-12-13 20:19
I can reproduce this on 3.0.0 by opening controller applet and attempting to exit it. I think it's a general applet exit problem.
Not sure whether this fall-through is intended or not, but adding a break there doesn't fix it.
https://github.com/Atmosphere-NX/Atmosphere/blob/f9a199557cf3b8269342ef0aa7b7e5f289bcad71/stratosphere/pm/source/impl/pm_process_manager.cpp#L436-L440

**Comment by misson20000** [comment] 2019-12-13 20:25
Suspecting that this codepath never actually cleans up process on <5.0.0, so the thread busyloops servicing the same process exit signal over and over. Not sure what the intended behavior here is though...
https://github.com/Atmosphere-NX/Atmosphere/blob/f9a199557cf3b8269342ef0aa7b7e5f289bcad71/stratosphere/pm/source/impl/pm_process_manager.cpp#L414-L438

**Closed** 2019-12-13 21:35 UTC
