### ISSUE TITLE
Monster Hunter Rise DLC content Crash

### ISSUE THREAD

**Issue by RushChill** [Atmosphere-NX/Atmosphere#1431] opened 2021-04-11 18:18 UTC
**What's the issue you encountered?**

After updating Atmosphere to 19.0, I opened MonHun Rise and when the program starts loading the DLC content it crashes.

**How can the issue be reproduced?**

Loading the Monster Hunter Rise game (digital version) with DLC content

Crash Report

Nintendo System Error Message: The Software Was Closed Because An Error Occurred

**System Firmware Version**
12.0.X

**Environment?**
    What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate v5.5.5
    Official release or unofficial build:
    Official release version 0.19.x
    Do you have additional kips or sysmodules you're loading: No (eliminated the atmosphere/contents folder before turning on the system
    Homebrew software installed: [ daybreak, reboot_to_payload, kosmos_toolbox,  checkpoint, ftspd_pro, ftspd_classic, jksv, all_in_one_update ]
   Sigpatches updated for 12.0

**Additional context?**
    After updating to 19.0, I cannot enter to emuMMC, only via fusee_primary

**Comment by SciresM** [comment] 2021-04-11 18:20
Checked for corrupted data? Redownloaded the dlc from the eshop?

**Comment by RushChill** [comment] 2021-04-11 21:50
> Checked for corrupted data? Redownloaded the dlc from the eshop?

Yeah, already did both and nothing, it crashes in the same load screen

**Comment by urherenow** [comment] 2021-04-12 02:55
Whether nor not your content is legit, do you have reason to have FS/ES patches on your system? I don't know the details, but the latest patches were released like 4 or 5 times last night. If you have any of those on your system, I would try to re-download and install them again to see if it takes care of your issue here.

**Comment by masagrator** [comment] 2021-04-12 10:04
> Sigpatches updated for 12.0

Piracy is not supported.

**Comment by SciresM** [comment] 2021-04-12 21:14
Can the generated crash report be uploaded, please?

**Comment by SciresM** [comment] 2021-04-13 00:16
Closing, because this is probably the content enumeration issue I just fixed in 0.19.1.

If the error continues to occur with 0.19.1, please let me know, and I'll try to get someone to reproduce it.

**Closed by SciresM** 2021-04-13 00:16 UTC
