### ISSUE TITLE
Always getting error 2168-0000 (0xa8) when open hbmenu (album)

### ISSUE THREAD

**Issue by yovin** [Atmosphere-NX/Atmosphere#1727] opened 2021-12-02 15:56 UTC
What's the issue you encountered?
Hello, I am having an issue with hbmenu or when openning album, it always getting error 2168-0000 (0xa8)

added:

How can the issue be reproduced?
When open the album

Crash Report
Error Code : 2168-0000 (0xa8)
Program : 010000000000100D
Firmware : 13.2.0 (Atmoshphere 1.2.5-master-1019bc54e)

System Firmware Version
13.2.0

Environment?

Atmosphere v1.2.5

The bootloader I use is fusee (payload injector)

Software added:
EdiZon SE
Goldleaf

Additional context?
If you need any more info, just ask. I have also Kept the same software on each update. It has happened to be previous in other versions but it normally gets fixed in the next update.

**Comment by SciresM** [comment] 2021-12-02 17:41
Upload the report.

fwiw -0000 indicates something more deeply wrong with your environment than usual.

**Comment by yovin** [comment] 2021-12-03 16:19
![photo_2021-12-03_23-18-51](https://user-images.githubusercontent.com/53088921/144636205-394818f5-39d4-4f7c-a487-1e63d9dbec86.jpg)

**Comment by SciresM** [comment] 2021-12-03 16:31
Upload the actual report file this generated, please? 

From atmosphere/crash_reports or atmosphere/fatal_reports.

**Comment by yovin** [comment] 2021-12-04 04:42
[01638548262_010000000000100d.log](https://github.com/Atmosphere-NX/Atmosphere/files/7653304/01638548262_010000000000100d.log)

**Comment by yovin** [comment] 2021-12-04 04:43
Sorry, this is the actual report. Thanks

**Comment by MagnumFang** [comment] 2021-12-05 14:38
I have this exact same issue

**Comment by sanselon** [comment] 2021-12-06 09:24
Hello, same here

**Comment by SciresM** [comment] 2021-12-06 09:39
This seems more than anything like your hbmenu nro is corrupted for some reason, tbh. Gonna tenatively close this, "undefined instruction" inside hbmenu is pretty nonsense/unreproducible locally (creport should be picking up hbmenu module name, too, not using a fallback build-id).

I recommend making sure your SD is formatted as FAT32 and re-extracting latest release zip, come to discord for further support if the problem isn't resolved by this.

**Closed by SciresM** 2021-12-06 09:39 UTC

**Comment by yovin** [comment] 2021-12-07 13:39
Can i get discord link?

**Comment by yovin** [comment] 2021-12-07 13:40
Can i get discord link?
