### ISSUE TITLE
Waking up from sleep mode still doesn't work on switch version 6.0.1

### ISSUE THREAD

**Issue by Pixelman546** [Atmosphere-NX/Atmosphere#235] opened 2018-10-20 03:24 UTC
Horizon OS 6.0.1 and Atmosphere 0.7.1
Waking from sleep will work only if my switch sits for under 2 minutes. Anywhere above that and it gives me a blank black screen when attempting to wake it. The only fix I have found was a hard reboot. I tried with Atmosphere 0.7.0 and 0.7.1 and got same results. Is this a bug? Or am I doing something wrong? I have the sd card set up correctly to fat32 and loaded with hekate and Atmosphere. Fusee.bin files are on root, and everything else homebrew related works just fine. Any help is greatly appreciated.

**Comment by SciresM** [comment] 2018-10-20 06:09
I'll do some more testing -- I don't think I've experienced anything like this though, I've spent a lot of time testing sleep mode.

**Comment by SciresM** [comment] 2018-10-21 07:17
I can't repro. Left my device in sleep for 8 hours today, woke it up, 6.0.1. Are you using Choi Dujour? Do you have any extra modules besides the base set included in the release installed?

**Comment by Pixelman546** [comment] 2018-10-21 15:28
Huh. I have the base installation, no extra modules, but I can't say I know what Choi Dujour is.

**Comment by Sonlen1414** [comment] 2018-10-21 15:35
https://www.reddit.com/r/NintendoSwitch/comments/9j9xne/warning_switch_sleep_mode_issue_possibly_related/

There seems to be bugs with stock firmware and 6.0+ with Sleep mode, I don't think it is necessarily a CFW issue, maybe it further enhances the problem if it already exists?

**Comment by SciresM** [comment] 2018-10-22 21:22
Tentatively closing due to inability to reproduce...re-open if it seems like it's actually an atmosphere issue.

**Closed** 2018-10-22 22:14 UTC

**Comment by Pixelman546** [comment] 2018-10-23 05:18
This issue was fixed for me following the recent 0.7.2. Thank you for the fix!
