### ISSUE TITLE
0.13.0 Black Screen

### ISSUE THREAD

**Issue by Samekas123** [Atmosphere-NX/Atmosphere#1082] opened 2020-07-10 12:16 UTC
## Bug Report
Since version 0.13.0 I can't boot into the atmosphere, I get a black screen. I have FAT32, tried also with fuseprimary and same thing happens black screen but this time with brightness. Going back to the version 12 everything works fine.

### What's the issue you encountered?

Black screen initiating atmosphere. 

### How can the issue be reproduced?

Inject payload using last henkate (5.3.0)
Initiate SysNAND or EmuNAND (both on 10.0.4), or fuse.
Black screen

### Crash Report
No crash reports.
### System Firmware Version

10.0.4</br>

### Environment?

Hekate 5.3.0
Using Official Build
Also tested with sdcreator
### Additional context?

It's only on this version I can't boot, on the others versions I can boot fine.

**Comment by Samekas123** [comment] 2020-07-10 16:31
Same problem being reported here: https://github.com/Atmosphere-NX/Atmosphere/issues/1053

**Comment by Mindinfinity** [comment] 2020-07-11 07:44
I had the same issue. After Formatting SD and making sure my Horizon Switch (Sysnand booted via normally, not RCM) was on latest firmware and my Emummc was on latest issue was resolved.

**Comment by Samekas123** [comment] 2020-07-11 12:41
> I had the same issue. After Formatting SD and making sure my Horizon Switch (Sysnand booted via normally, not RCM) was on latest firmware and my Emummc was on latest issue was resolved.

I have everything on latest version. I tried clean install many times.

**Comment by Samekas123** [comment] 2020-07-11 13:00
Looks like SciresM fixed this: https://github.com/Atmosphere-NX/Atmosphere/commit/1473adf5c4a6b7d833ceff60e8d8c3ed0fd02ab9 but I don't know how to compile it :/

**Comment by cheesycod** [comment] 2020-07-13 03:27
Firstly install devkitpro using https://switchbrew.org/wiki/Setting_up_Development_Environment, then follow docs/building.md

**Comment by Samekas123** [comment] 2020-07-13 10:44
> Firstly install devkitpro using https://switchbrew.org/wiki/Setting_up_Development_Environment, then follow docs/building.md

Thank you, I tried to compile it but getting some errors. Thanks anyways, was a good try! I will just wait for next build and hopefully this fixes will be merged.

**Comment by cheesycod** [comment] 2020-07-13 12:44
You have to use the latest master commit of libnx as well fyi

**Comment by Feralzi** [comment] 2020-07-17 02:52
Okay so idk why no one has said anything about this. Ill go straight to the point, theres a folder inside the nintendo folder on the root of your sd card, DELETE the private files. For some reason, after my switch updated, those two files popped up, and it wouldnt let me boot into my atmosphere (basically a black screen after the injection). Literally i spent 3 hours trying to find the source; had to use a second sd card that is formatted to check if my switch still runs atmosphere lol. Hope this helps.

**Comment by marc-maurer** [comment] 2020-07-17 11:16
@Feralzi For me its not solving the problem.

**Comment by Samekas123** [comment] 2020-07-17 11:24
> Okay so idk why no one has said anything about this. Ill go straight to the point, there's a folder inside the Nintendo folder on the root of your SD card, go inside the content folder, DELETE the "private" files. For some reason, after my switch updated, those two files popped up, and it wouldn't let me boot into my atmosphere (basically a black screen after the injection). Literally i spent 3 hours trying to find the source; had to use a second SD card that is formatted to check if my switch still runs atmosphere lol. Hope this helps.

Thank you for trying to help but still not working here.

> @Feralzi For me its not solving the problem. 
I went back to Atmosphère 0.12.0 and it is now working again.

Yep, going to version 12 solves it for me too.

**Comment by shmimeow** [comment] 2020-07-20 00:20
> @Feralzi For me its not solving the problem.
> 
> I went back to Atmosphère 0.12.0 and it is now working again.

#491

**Comment by shmimeow** [comment] 2020-07-20 00:20
> @Feralzi For me its not solving the problem.
> 
> I went back to Atmosphère 0.12.0 and it is now working again.

#metoo

**Comment by Samekas123** [comment] 2020-07-21 06:36
I don't know why still any dev replied to this thread.

**Comment by punkgamer69** [comment] 2020-07-21 23:40
> @Feralzi For me its not solving the problem.
> 
> I went back to Atmosphère 0.12.0 and it is now working again.

Same here. Going back to version 12 solves it for me.

**Comment by SciresM** [comment] 2020-07-21 23:41
So far as I know this is a duplicate of #1053, which I fixed a while ago. If it's not fixed in 0.14.0, re-open.

**Closed by SciresM** 2020-07-21 23:41 UTC
