### ISSUE TITLE
Cheatcode feature: give me a way to increment and decrement float damn it

### ISSUE THREAD

**Issue by ImanCol** [Atmosphere-NX/Atmosphere#2243] opened 2023-11-28 18:54 UTC
I need to rotate and move objects and most are represented as floats

**Comment by SciresM** [comment] 2023-11-28 20:39
Duplicate of #934, which stalled on someone giving me a real spec. Also, you didn't use the issue templates.

**Closed by SciresM** 2023-11-28 20:39 UTC

**Comment by ImanCol** [comment] 2023-11-28 21:17
You solved it right?  This article is from 4 years ago.

**Comment by ImanCol** [comment] 2023-11-28 21:25
Modify Transform or 3-axis Vectors that are float.

Ah, that's what I meant by objects and their properties.  I also see many uses for it that I stopped being able to implement because floats cannot be increased or decreased in cheatcode.
