### ISSUE TITLE
CCPLEX 5.1.0 bug

### ISSUE THREAD

**Issue by sandhoners123** [Atmosphere-NX/Atmosphere#198] opened 2018-08-22 17:05 UTC
Exosphere does not load on 5.1.0 and gets stuck at powering on CCPLEX. Is this because of autorcm or is this a true issue. If it is a true issue, can you please fix it for the 0.7 release

**Comment by hexkyz** [comment] 2018-08-22 20:44
I'm closing this issue because it's a duplicate of #194.
This is indeed an issue (not related to AutoRCM) which is already being fixed for the 0.7 release.

**Closed by hexkyz** 2018-08-22 20:44 UTC
