### ISSUE TITLE
EmuNand fusee.bin with Atmosphère 1.4.0 (pre-release) boot issue

### ISSUE THREAD

**Issue by whitezombie2000** [Atmosphere-NX/Atmosphere#1964] opened 2022-10-15 22:17 UTC
### What's the issue you encountered?

I updated to the latest Atmosphère 1.4.0 (pre-release), fusee.bin, and firmware 15.0.0 via Daybreak, deleted all old Atmosphère files and replaced with the new 1.4.0 (pre-release) files. When using a partition based EmuNand with Atmosphère 1.4.0 (pre-release), FW 15.0.0, using payload=bootloader/payloads/fusee.bin with hekate_ipl.ini, or chaining Hekate and choosing fusee.bin from payload, or loading fusee.bin directly with TegraRCMGui, it fails to boot, shows Atmosphere boot screen, fails to get to switch logo, gets a black screen, and requires a hard shutdown.

### How can the issue be reproduced?

Issue can be reproduced by installing FW 15.0.0, clean Atmosphère 1.4.0 1.4.0 (pre-release) files, and Hekate v5.9.0. Injecting fusee.bin directly with TegraRCMGui, or chain booting fusee.bin with Hekate. Using a partition based EmuNandBoot, inject fusee.bin via TegraRCMGui, shows the Atmosphere boot screen, fails to get to the switch logo, gets a black screen, and requires a hard shutdown. Same issue can be reproduced if you use Hekate to chain fusee.bin via Hekate and choosing payload, selecting fusee.bin, or use payload=bootloader/payloads/fusee.bin with hekate_ipl.ini. 

The only way I have gotten it boot successfully is by using fss0=atmosphere/package3 in my hekate_ipl.ini file. I downgraded the firmware via Daybreak back to 14.1.2 and everything works fine on 14.1.2 with the 1.4.0 (pre-release) files. I upgraded back to 15.0.0, put in clean files, and the issue persists. No matter what boot method I use with fusee.bin I always get the black screen.

### System Firmware Version
15.0.0

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: 
Launched fusee.bin with TegraRCMGui, launched fusee.bin with Hekate via payload=bootloader/payloads/fusee.bin with hekate_ipl.ini, launched fusee.bin via Hekate and choosing payload, selecting fusee.bin

- EmuMMC or SysNAND:
partition based EmuMMC

**Comment by SciresM** [comment] 2022-10-15 22:25
I cannot actually reproduce this. My console boots into 15.0.0 sysmmc and emummc fine using fusee.bin, both directly and chained from hekate.

I always suspect this happens due to e.g. not updating fusee correctly or due to exFAT issues.

I know there's no issue fundamentally with fusee, btw -- if the console is getting past the atmosphere logo literally at all it's not a fusee problem.

**Comment by whitezombie2000** [comment] 2022-10-15 22:26
I should also mention I'm using FAT32.

**Comment by SciresM** [comment] 2022-10-15 22:27
Yeah. Honestly, if you want to debug on discord, feel free to DM me (SciresM#0524), but I really don't believe these are actual code problems. I'll re-open given compelling evidence that it's actually a problem with fusee, but in the mean-time if you can boot via hekate...boot via hekate?

**Comment by mrdude2478** [comment] 2022-10-16 01:14
I know there's no issue fundamentally with fusee, btw -- if the console is getting past the atmosphere logo literally at all it's not a fusee problem.

It doesn't get past the Atmosphere logo - it shows the Atmosphere boot screen and then goes black before it gets to the logo, and therefore doesn't get to the switch logo either.

**Comment by SciresM** [comment] 2022-10-16 01:37
@whitezombie2000 @mrdude2478 Is the issue fixed using this fusee binary?

[fusee.bin.zip](https://github.com/Atmosphere-NX/Atmosphere/files/9793432/fusee.bin.zip)

**Comment by whitezombie2000** [comment] 2022-10-16 01:45
I just reinstalled FW 15 and that worked via chain booting. Let me try direct and editing the hekate_ipl.ini file.

**Comment by whitezombie2000** [comment] 2022-10-16 01:54
OK, chain booting that new fusee.bin via Hekate and choosing payload works, calling it from payload=bootloader/payloads/fusee.bin with hekate_ipl.ini works, and injecting it directly with TegraRCMGui works. What did you change?

**Comment by SciresM** [comment] 2022-10-16 01:55
I'll commit the change after dinner, and it will make it into 1.4.0 non-prerelease. 

The nogc patch for exFAT firmware had an off-by-one...so I guess you were installing exFAT firmware even though you weren't using exFAT?

**Comment by whitezombie2000** [comment] 2022-10-16 01:58
When installed the firmware via Daybreak I always choose Preserve Settings and Install (FAT32 + exFAT).

**Comment by SciresM** [comment] 2022-10-16 02:02
Yeah, I tested booting into non-exFAT emummc, tested booting into exFAT emummc, and tested nogc...but I don't actually use exFAT firmware so this escaped testing.

My apologies both for the issue and the insistence that it wasn't a code issue. The clarification that it wasn't getting past the ams logo was very helpful.

Still, do reach out on discord! I am a lot faster there and also provide support for a lot of issues that wouldn't be covered on GitHub.

**Comment by mrdude2478** [comment] 2022-10-16 02:36
Yep, thanks for fixing this. I tried it and it's working fine now.

**Comment by tbensonwest** [comment] 2022-10-17 06:49
Thought I was going nuts. Exactly the issue I was facing yesterday. Will try this method later.

**Comment by Inclsevd** [comment] 2022-10-17 14:10
I also got hit with this and couldn't figure it out but finally found this issue, everything is working smoothly now. Thanks!

**Comment by hsuanpai** [comment] 2022-10-17 15:56
Try this boot loader parameter.
I had boot success with 15.0.0 of AMS 1.4.0. of EMUMMC.

[CFW (EMUNAND)]
emummcforce=1
fss0=atmosphere/package3
kip1patch=nosigchk
atmosphere=1
logopath=bootloader/bootlogo.bmp
icon=bootloader/res/emunand.bmp
id=2

**Comment by hsuanpai** [comment] 2022-10-17 16:42
> @whitezombie2000 @mrdude2478 Is the issue fixed using this fusee binary?
> 
> [fusee.bin.zip](https://github.com/Atmosphere-NX/Atmosphere/files/9793432/fusee.bin.zip)

Updated this fixed fusee bin is also workable.

**Comment by the-importer** [comment] 2022-10-17 18:25
Same issue on both my Switch systems (OG V1 and Switch Lite with modchip). It seems totally random however, sometimes it boots, sometimes I get a black screen.

**Comment by zemixe** [comment] 2022-10-17 18:48
> Try this boot loader parameter with hekate_ipl.ini . I had boot success with 15.0.0 of AMS 1.4.0. of EMUMMC.
> 
> [CFW (EMUNAND)] emummcforce=1 fss0=atmosphere/package3 kip1patch=nosigchk atmosphere=1 logopath=bootloader/bootlogo.bmp icon=bootloader/res/emunand.bmp id=2

Irrelevant and piracy is not supported.

> Same issue on both my Switch systems (OG V1 and Switch Lite with modchip). It seems totally random however, sometimes it boots, sometimes I get a black screen.

So download the fixed fusee.bin above and test it. However this issue should not be random, it should be pretty clear cut as to whether you can boot or not.

**Comment by AntiFly** [comment] 2022-10-18 12:10
> > @whitezombie2000 @mrdude2478 Is the issue fixed using this fusee binary?
> > [fusee.bin.zip](https://github.com/Atmosphere-NX/Atmosphere/files/9793432/fusee.bin.zip)
> 
> Updated this fixed fusee bin is also workable.

this new binary fixed my problem not booting at all into the CFW.
I got always the error that there is an error with warmboot...

{-- Custom Firmware --}
[NSW emuMMC]
payload=bootloader/payloads/fusee.bin
kip1patch=nosigchk
atmosphere=1
emummcforce=1
logopath=bootloader/bootlogo.bmp
icon=bootloader/res/icon_atmo.bmp

on not updated cfw yet. (ofw of course)

**Comment by zemixe** [comment] 2022-10-18 15:08
> > > @whitezombie2000 @mrdude2478 Is the issue fixed using this fusee binary?
> > > [fusee.bin.zip](https://github.com/Atmosphere-NX/Atmosphere/files/9793432/fusee.bin.zip)
> > 
> > 
> > Updated this fixed fusee bin is also workable.
> 
> this new binary fixed my problem not booting at all into the CFW. I got always the error that there is an error with warmboot...
> 
> {-- Custom Firmware --} [NSW emuMMC] payload=bootloader/payloads/fusee.bin kip1patch=nosigchk atmosphere=1 emummcforce=1 logopath=bootloader/bootlogo.bmp icon=bootloader/res/icon_atmo.bmp
> 
> on not updated cfw yet. (ofw of course)
> 
> But still has the error that there is just the screen lighted on with "black". this happens a lot now.. I use system reboot or shutdown and on boot screen just lighted on with nothing.

This is impossible to understand I'm afraid, the hekate config you posted is terrible and does nothing when using fusee.bin. Additionally, piracy is not supported.

**Comment by AntiFly** [comment] 2022-10-18 17:02
lol
starting cfw piracy... weirdo ;)
I am not in the mood discuss with you man. take care
anyway. since 15.0 restarting nsw or shutdown and boot new is ending 7/10 up in a black screen where just the display is enlighted. so you may be now able to understand, if not go sleeping again ;)

**Comment by SciresM** [comment] 2022-10-18 17:29
Closing this because it's resolved by 05fee5d.

**Closed by SciresM** 2022-10-18 17:29 UTC
