### ISSUE TITLE
Crash/Fatal Error When running SYSbot Auto Host

### ISSUE THREAD

**Issue by JRandeezy** [Atmosphere-NX/Atmosphere#968] opened 2020-05-27 10:05 UTC
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

[ * ]</br>
[ Note: If the bug or crash you encountered is related to; ]</br>
[ - software used to make "backups", ]</br>
[ - software explicitly distributed for piracy, etc ]</br>
[ then contributors will not provide support for your issue and your issue will be closed. ]</br>

### What's the issue you encountered?

[ Was running Auto-Hosting Dens in Pokemon Sword with SYSBot and after about 20 minutes Atmosphere would crash. After rebooting and attempting to run it again, after about 20 minutes the same error would occur. ]</br>
[ I did not make any changes to Atmosphere itself]</br>
[ N/A ]</br>

### How can the issue be reproduced?

[ * ]</br>
[ Step1. Boot into SYS, 
Step2. Open pokemon sword load save file
Step3. Connect Online and Run SYSBot (RaidBot)
Step 4. Bot runs fine for about 2 minutes then system crashes. ]</br>

### Crash Report

[ Atmosphère Fatal Report (v1.1):
Result:                          0x41001 (2001-0520)

Program ID:                      010000000000000d
Process Name:                    dmnt
Firmware:                        10.0.3 (Atmosphère 0.12.0-master-7bc0250c)
General Purpose Registers:
Start Address:                   0000000000000000
Stack Trace:
        ReturnAddress[00]:       0000000000000000
        ReturnAddress[01]:       0000000000000000
        ReturnAddress[02]:       0000000000000000
        ReturnAddress[03]:       0000000000000000
        ReturnAddress[04]:       0000000000000000
        ReturnAddress[05]:       0000000000000000
        ReturnAddress[06]:       0000000000000000
        ReturnAddress[07]:       0000000000000000
        ReturnAddress[08]:       0000000000000000
        ReturnAddress[09]:       0000000000000000
        ReturnAddress[10]:       0000000000000000
        ReturnAddress[11]:       0000000000000000
        ReturnAddress[12]:       0000000000000000
        ReturnAddress[13]:       0000000000000000
        ReturnAddress[14]:       0000000000000000
        ReturnAddress[15]:       0000000000000000
        ReturnAddress[16]:       0000000000000000
        ReturnAddress[17]:       0000000000000000
        ReturnAddress[18]:       0000000000000000
        ReturnAddress[19]:       0000000000000000
        ReturnAddress[20]:       0000000000000000
        ReturnAddress[21]:       0000000000000000
        ReturnAddress[22]:       0000000000000000
        ReturnAddress[23]:       0000000000000000
        ReturnAddress[24]:       0000000000000000
        ReturnAddress[25]:       0000000000000000
        ReturnAddress[26]:       0000000000000000
        ReturnAddress[27]:       0000000000000000
        ReturnAddress[28]:       0000000000000000
        ReturnAddress[29]:       0000000000000000
        ReturnAddress[30]:       0000000000000000
        ReturnAddress[31]:       0000000000000000
 ]</br>
[ I may need help creating a gist if requested ]</br>
[N/A ]</br>

### System Firmware Version

10.0.3</br>
[ Replace X's with system firmware version at time of crash. ]</br>
[ You can find your firmware version in the Settings -> System, under "System Update". ]</br>
[ If it says "Update Pending", you can clear the pending update by rebooting to Maintenance Mode. ]</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: hekate
- Official release or unofficial build: Official Release
  - [ Official release version 5.2.1 (or) unofficial build ]
  - [ N/A] 
     - [ N/A ]
     - [ N/A ]
- Do you have additional kips or sysmodules you're loading: SYSBot? (excuse my ignorance)
- Homebrew software installed: [ Checkpoint, Capture Sight, FTPD, Luxray, NX-Shell, NX-Themes]

### N/a?

- Additional info about your environment: At home next to PC
- [ N/A]

**Comment by SciresM** [comment] 2020-05-27 10:14
Duplicate of #938.

**Closed by SciresM** 2020-05-27 10:14 UTC
