### ISSUE TITLE
Pre-Release

### ISSUE THREAD

**Issue by musgrove-ernest** [Atmosphere-NX/Atmosphere#2039] opened 2023-02-23 02:07 UTC
I am still getting "fatal error occurred when running Fusee.  Unable to identify package1!"

I just downloaded and tried on my switch please let me know what you need and i will try to provide for you guys.

Also, kick ass job on getting a pre-release out so quickly

**Comment by SciresM** [comment] 2023-02-23 02:08
I think you are using old fusee, not the one included with the pre-release. The pre-release fusee works fine for me (and a few others on discord)...please double check that you've actually updated the file you're injecting, especially if you chainload via hekate

**Comment by stinkynate** [comment] 2023-02-23 02:15
I can confirm I'm also still seeing "Unknown pkg1 version". It's my first time trying to update Atmosphere though so there's that.

I copied the contents of the zip to root, overwriting any files that match. Then dropped the new fusee.bin in bootloader/payloads

**Comment by SciresM** [comment] 2023-02-23 02:16
"Unknown pkg1 version" is a hekate error. If you use hekate, you'll need to wait for it to be updated.

**Comment by musgrove-ernest** [comment] 2023-02-23 02:18
Regardless thank you for the quick respond and work

**Comment by bdawg1989** [comment] 2023-02-23 02:39
I use Hekate too.  Wonder if I can use something different until CTaer updates

**Comment by SciresM** [comment] 2023-02-23 02:39
I'm going to close this issue; I boot exclusively with fusee (obviously, since I make it), and I had someone else verify the release is fine.

**Closed by SciresM** 2023-02-23 02:39 UTC

**Comment by v1993** [comment] 2023-02-23 09:41
Hekate 6.0.2 is now live and supports latest firmware revision.
