### ISSUE TITLE
panic occured while running atmosphere

### ISSUE THREAD

**Issue by LunaerD** [Atmosphere-NX/Atmosphere#696] opened 2019-11-11 17:51 UTC
## Bug Report

N/A

### What's the issue you encountered?

 [Today I downloaded an app from the hb app store and then atmosphere crashd and when I try to launch emummc atmosphere says "panic occured while running atmosphere".</br>
I tried to delete the .nro app with my pc but I can't. </br>

### How can the issue be reproduced?

 * </br>
 1-Go to the hb app store
   2-download the BrowseNx app
   3- at the end of the download it crash. </br>

### Crash Report

</br>
https://gist.github.com/LunaerD/a1a4ba377d43536f1ca79fb3061c7e59</br>
</br>

### System Firmware Version

0.9.4</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate
- Official release or unofficial build: official release
  -  Official release version 5.0.2
- Do you have additional kips or sysmodules you're loading: nope
- Homebrew software installed:   no

### Additional context?

- Additional info about your environment: a friend installed the crack for me and it worked perfectly before the app download

**Comment by SciresM** [comment] 2019-11-13 21:09
Seems like a duplicate of #695?

**Closed by SciresM** 2019-11-13 21:09 UTC

**Comment by LunaerD** [comment] 2019-11-13 21:33
> ## Bug Report
> N/A
> 
> ### What's the issue you encountered?
> [Today I downloaded an app from the hb app store and then atmosphere crashd and when I try to launch emummc atmosphere says "panic occured while running atmosphere".
> 
> I tried to delete the .nro app with my pc but I can't.
> 
> ### How can the issue be reproduced?
> * 
> 
> 1-Go to the hb app store
> 2-download the BrowseNx app
> 3- at the end of the download it crash.
> 
> ### Crash Report
> 
> https://gist.github.com/LunaerD/a1a4ba377d43536f1ca79fb3061c7e59
> 
> ### System Firmware Version
> 0.9.4
> 
> ### Environment?
> * What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate
> * Official release or unofficial build: official release
>   
>   * Official release version 5.0.2
> * Do you have additional kips or sysmodules you're loading: nope
> * Homebrew software installed:   no
> 
> ### Additional context?
> * Additional info about your environment: a friend installed the crack for me and it worked perfectly before the app download



> Seems like a duplicate of #695?

Nope because my crash is during the loading of atmosphere after I send a payload into my switch so I can't even load the crack

**Comment by SciresM** [comment] 2019-11-13 21:37
"Load the crack" - what?

Are you sure you're using a completely stock latest atmosphere release downloaded from ams repo? What version of atmosphere are you using?

Your crash report is an assert in the bsdsockets sysmodule, which suggests some homebrew is doing something weird.

What folders do you have in /atmosphere/titles?

**Comment by LunaerD** [comment] 2019-11-13 21:48
> "Load the crack" - what?
> 
> Are you sure you're using a completely stock latest atmosphere release downloaded from ams repo? What version of atmosphere are you using?
> 
> Your crash report is an assert in the bsdsockets sysmodule, which suggests some homebrew is doing something weird.
> 
> What folders do you have in /atmosphere/titles?

I'm using the latest atmosphere releases for the 9.0.1 switch, and all of the folders are the same as when I installed the whole thing except the .nro app that I cannot delete.

**Comment by ZachyCatGames** [comment] 2019-11-13 22:05
Delete /atmosphere/titles/00FF747765616BFF. BrowseNX comes with a sysmodule that causes a fatal error on startup on 9.0+.

**Comment by Grayfoxst** [comment] 2020-01-15 15:04
Hello , im having the same issue , however when i browse the /Atmosphere/titles/ the folder is empty , and im not seeing any hidden file. any ideas?

**Comment by dennthecafebabe** [comment] 2020-01-15 15:37
`atmosphere/titles` is called `atmosphere/contents` now

**Comment by Grayfoxst** [comment] 2020-01-15 16:09
Thanks i already resolve it by doing it !!!

**Comment by Bastiongg** [comment] 2020-01-16 04:01
@ZachyCatGames Thank you this worked for me 💯

**Comment by DSMan97** [comment] 2020-01-30 22:50
> > Delete /atmosphere/titles/00FF747765616BFF, that’ll solve the error your getting on boot. BrowseNX comes with a sysmodule that causes a fatal error on startup on 9.0+.
> > @ZachyCatGames Thank you this worked for me 💯


So 00FF747765616BFF correspond to BrowseNX ?? Jus to know for the next timw, thanks in advance :)

**Comment by msamkov** [comment] 2020-05-20 09:54
Помогло удаление каталога /atmosphere/contents/00FF747765616BFF
