### ISSUE TITLE
crash on load up

### ISSUE THREAD

**Issue by pito4evr** [Atmosphere-NX/Atmosphere#774] opened 2019-12-21 20:12 UTC
i just updated the switch to 9.1 and am running 10.1 but it crashes after the nintendo logo
![20191221_150659](https://user-images.githubusercontent.com/55258179/71313273-53a4cd80-2404-11ea-86d9-d98af433f39a.jpg)

**Comment by fincs** [comment] 2019-12-21 20:13
qlaunch crashed. Remove custom themes and try again.

**Comment by pito4evr** [comment] 2019-12-21 20:15
how would i remove the custom themes since i cant load it up

**Comment by fincs** [comment] 2019-12-21 20:15
Take out the SD card, pop it in your pc and delete /atmosphere/contents/0100000000001000.

**Comment by pito4evr** [comment] 2019-12-21 20:18
that worked. thanks. i also just got a message saying game cart could not be read.

**Comment by fincs** [comment] 2019-12-21 20:18
Edit /atmosphere/config/BCT.ini and add nogc=0 to the end of it.

**Comment by pito4evr** [comment] 2019-12-21 20:20
i dont really care about the fuses since i dont plan on downgrading. Also would i reinstal themes like before or would have have to do an extra step on the newfirmware

**Comment by fincs** [comment] 2019-12-21 20:23
You'd need to get new themes that are built for your system version. For this reason, custom themes aren't really recommended; they're more of a hassle than they are worth.

Also, since this issue is now solved I'm closing it. This issue tracker is for reporting confirmed Atmosphère bugs and feature requests. Next time an issue arises, please check first the provided user support link that appears when you try to create an issue ("Please ask questions here...").

**Closed by fincs** 2019-12-21 20:23 UTC
