### ISSUE TITLE
Black screen upon booting Atmosphère 0.14.0

### ISSUE THREAD

**Issue by ThatNintendoNerd** [Atmosphere-NX/Atmosphere#1102] opened 2020-08-01 23:47 UTC
### What's the issue you encountered?

Upon booting the latest release of Atmosphère, after the colored Atmosphère splash screen is displayed the console hangs on a black screen.

### How can the issue be reproduced?

Add contents of `atmosphere-0.14.0-master-a82914d5+hbl-2.3.4+hbmenu-3.3.0.zip` to the root of the microSD card and update `fusee_primary.bin`.

### Crash Report

N/A

### System Firmware Version

10.0.4

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
fusèe
- Official release or unofficial build: 
  - [ Official release version 0.14.0 ]
- Do you have additional kips or sysmodules you're loading: No
- Homebrew software installed: None

### Additional context?
- microSD card format is FAT32 formatted with guiformat with a 64 KiB allocation unit size.
- No other files on microSD card besides contents of Atmosphère 0.14.0 release ZIP.
- `fusee_primary.bin` has been updated with the 0.14.0 release.
- Reformatting the card and adding the Atmosphère 0.13.0 release contents to the root of the microSD card as well as changing `fusee_primary.bin` to the 0.13.0 release allows the console to boot fully.

**Comment by SciresM** [comment] 2020-08-01 23:50
Is this sysmmc or emummc?

Either way, please contact me on discord (SciresM#0524) for further support.

**Comment by ThatNintendoNerd** [comment] 2020-08-01 23:50
This is sysMMC. And I will do so.

**Comment by Slluxx** [comment] 2020-08-02 00:47
It works for me on 10.0.4 (same firmware as @ThatNintendoNerd) but i know one more who has problems with 0.14.0

**Comment by muxi1** [comment] 2020-08-02 07:41
The same problem under the same conditions applies to me under FW 9.2.0, but under a partition emuMMC.

**Comment by spitfire** [comment] 2020-08-02 08:41
same here, 1.0.1.0 sysMMC

**Comment by matteopiccioni** [comment] 2020-08-02 08:46
Same problem for me
sysmmc, sd fat32

**Comment by THZoria** [comment] 2020-08-02 09:05
same problem, test with 2 SD, one format in exFat (no other file)
and another SD format in fat32 (no other file) with also a
black screen via fusee primary / hekate in sysmmc

**Comment by pontostroy** [comment] 2020-08-02 09:16
Same for me with 10.1.0 sysMMC, exfat SD
Also I build master branch with the same result.

**Comment by pixeltester** [comment] 2020-08-02 09:30
Same issue on sysnand and firmware 9.2.0

**Comment by SciresM** [comment] 2020-08-02 09:31
Commenting "issue occurs" is largely unhelpful. A few people have volunteered to test; it'll be fixed either as soon as I can reproduce it or in the next few days.

**Comment by maciak** [comment] 2020-08-02 13:34
Hi.
I dont know if I have the same issue but for me it takes quite a while to boot. It gets stuck on color atmo logo for about a minute but then it boots fine. I'm on 10.0.0 btw

**Comment by ImportTaste** [comment] 2020-08-02 14:00
> Commenting "issue occurs" is largely unhelpful. A few people have volunteered to test; it'll be fixed either as soon as I can reproduce it or in the next few days.

Is there a way to generate some sort of debug log for you, then? There's no crash report.

**Comment by NicholeMattera** [comment] 2020-08-02 14:47
Not sure if this is related, but I was able to reproduce this issue by just adding an empty patch for loader. Just put the attached file (It's not a sigpatch it just contains "PATCHEOF") to sd:/atmosphere/kip_patches/loader_patches/, and it should produce a black screen after the Atmosphere splash screen.

[4D9C6D6993BF5BF058843BE072C9819598865C79BF87674C63B6D248FA7A0BA4.zip](https://github.com/Atmosphere-NX/Atmosphere/files/5012307/4D9C6D6993BF5BF058843BE072C9819598865C79BF87674C63B6D248FA7A0BA4.zip)

**Comment by ImportTaste** [comment] 2020-08-02 14:54
It seems booting with hekate 5.3.2 works properly - doesn't produce the black screen. It's only with fusee-primary that things mess up.

**Comment by fincs** [comment] 2020-08-02 15:32
Fwiw, I have personally reproduced this issue with AMS 0.14.0 / fusee / sysver 10.1.0 without any loader patches (fake or not) being present.

**Comment by ZeroGwafa** [comment] 2020-08-02 15:49
> Fwiw, I have personally reproduced this issue with AMS 0.14.0 / fusee / sysver 10.1.0 (sysmmc) without any loader patches (fake or not) being present, i.e. only `default_nogc`.

Seconding this.  Had the same issue after updating.  Then wiped the SD card, and re-installed Atmosphere, changing only the BCT.ini file to disable nogc.  Black screen.  Removed that line from the BCT.ini file ,and it booted right up.

**Comment by hexkyz** [comment] 2020-08-02 17:47
Just to clarify, @ZeroGwafa are you now (after removing the nogc line) able to boot AMS fine every time?

**Comment by Bappsack** [comment] 2020-08-02 18:08
can also confirm the blackscreen on boot, tried with hekate and fg, fresh formated sd and default ams with no sys modules.

Latest FW, Fat32 Sysemmc

**Comment by SciresM** [comment] 2020-08-02 19:11
Managed to reproduce issue. Debugging with @hexkyz right now.

**Comment by SciresM** [comment] 2020-08-02 21:23
Figured out the issue. Fix shortly.

**Comment by SciresM** [comment] 2020-08-02 21:37
Hm, actually, only part of the issue was fixed by that. Soon enough.

**Closed** 2020-08-02 22:00 UTC
